<a href="https://colab.research.google.com/github/stalin99835/DUDL/blob/main/number_params.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import numpy as np

In [9]:
widenet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3),
)

deepnet  = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3),
)

print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [10]:
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.0859,  0.5331],
        [-0.2321, -0.4872]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.6717,  0.3243], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.4979, -0.2705],
        [-0.4449,  0.4485]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([ 0.5096, -0.2984], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.2074,  0.5414],
        [-0.4442,  0.0350],
        [-0.6065, -0.3397]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.2288, -0.2805, -0.4664], requires_grad=True))
 


In [25]:
numnodesinwide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numnodesinwide+= len(p[1])

print(numnodesinwide)

numnodesindeepnet = 0

for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numnodesindeepnet += len(paramVect)

print('There are %s nodes in the wide network' %(numnodesinwide))
print('There are %s nodes in the deep network' %(numnodesindeepnet))

for p in widenet.parameters():
  print(p)
  print(' ')

numparms = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('this has %s parameters' %(p.numel()))
    numparms +=p.numel()
    print(p.numel)


7
There are 7 nodes in the wide network
There are 7 nodes in the deep network
Parameter containing:
tensor([[-0.6941,  0.5919],
        [-0.6015, -0.0009],
        [-0.2867,  0.1567],
        [-0.2790,  0.6885]], requires_grad=True)
 
Parameter containing:
tensor([0.4091, 0.2097, 0.1515, 0.3424], requires_grad=True)
 
Parameter containing:
tensor([[-0.0749,  0.1661,  0.2372, -0.1557],
        [-0.2537, -0.2644,  0.3195, -0.4712],
        [ 0.2550,  0.2533, -0.4311,  0.2002]], requires_grad=True)
 
Parameter containing:
tensor([0.2047, 0.1398, 0.2452], requires_grad=True)
 
this has 8 parameters
<built-in method numel of Parameter object at 0x7f6a8f732bb0>
this has 4 parameters
<built-in method numel of Parameter object at 0x7f6a8f730680>
this has 12 parameters
<built-in method numel of Parameter object at 0x7f6a8f6a6660>
this has 3 parameters
<built-in method numel of Parameter object at 0x7f6a8f7306d0>


In [27]:
from torchsummary import summary
summary(widenet,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
